name: Node CI

on: [push, pull_request]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Groonga
      run: curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
    - run: npm i -g npm
    - run: npm ci
    - run: npm test

  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - run: brew install groonga pkg-config
    - run: npm i -g npm
    - run: npm ci
    - run: npm test
      env:
        PKG_CONFIG_PATH: /usr/local/opt/groonga/lib/pkgconfig

  windows-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Install Groonga
      shell: bash
      run: |
        export RELEASE_VERSION=9.0.8
        export ARCHIVE=groonga-${RELEASE_VERSION}-x64-vs2017.zip

        choco install -y curl 7zip.commandline
        curl -OL https://github.com/groonga/groonga/releases/download/v${RELEASE_VERSION}/${ARCHIVE}
        echo ${ARCHIVE}
        7z x ${ARCHIVE}
        rm ${ARCHIVE}
        mv groonga-* ../groonga
    - run: npm i -g npm
    - run: npm config set msvs_version 2019
    - run: npm i -g node-gyp
    - name: npm ci
      shell: bash
      run: |
        export GROONGA_PATH=${GITHUB_WORKSPACE}/../groonga
        npm ci
    - name: npm test
      shell: bash
      run: |
        export GROONGA_PATH=${GITHUB_WORKSPACE}/../groonga
        npm test

  publish:
    name: npm publish
    runs-on: ubuntu-latest
    needs: [ubuntu-test, macos-test, windows-test]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
    - name: Setup Groonga
      run: curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
      if: contains(github.ref, 'tags/v')
    - run: npm ci
      if: contains(github.ref, 'tags/v')
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      if: contains(github.ref, 'tags/v')
