name: Node CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Groonga
      run: curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
    - name: npm install and test
      run: |
        npm install
        npm test

  publish:
    name: npm publish
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Setup Groonga
      run: curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
      if: contains(github.ref, 'tags/v')
    - run: npm install
      if: contains(github.ref, 'tags/v')
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      if: contains(github.ref, 'tags/v')
